SQL_GET_MOVIES_BY_IDS = """SELECT * FROM"""
SQL_GET_SERIALS_BY_IDS = """SELECT * FROM"""

SQL_GET_FROM_PERSON_MOVIE_IDS = """SELECT * FROM"""
SQL_GET_FROM_PERSON_SERIAL_IDS = """SELECT * FROM"""

SQL_GET_FROM_GENRE_MOVIE_IDS = """SELECT * FROM"""
SQL_GET_FROM_GENRE_SERIAL_IDS = """SELECT * FROM"""

SQL_GET_FROM_MOVIEPERSONROLE_MOVIE_IDS = """SELECT * FROM"""
SQL_GET_FROM_SERIALPERSONROLE_SERIAL_IDS = """SELECT * FROM"""

SQL_GET_FROM_MOVIE_MOVIE_IDS = """SELECT * FROM"""
SQL_GET_FROM_SERIAL_SERIAL_IDS = """SELECT * FROM"""

queries = [
    SQL_GET_FROM_PERSON_MOVIE_IDS,
    SQL_GET_FROM_PERSON_SERIAL_IDS,
    SQL_GET_FROM_GENRE_MOVIE_IDS,
    SQL_GET_FROM_GENRE_SERIAL_IDS
    SQL_GET_FROM_MOVIEPERSONROLE_MOVIE_IDS,
    SQL_GET_FROM_SERIALPERSONROLE_SERIAL_IDS,
    SQL_GET_FROM_MOVIE_MOVIE_IDS,
    SQL_GET_FROM_SERIAL_SERIAL_IDS,
]