version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - 9200:9200
    volumes:
      - es_data:/data

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis
      - ./state/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    depends_on:
      - elasticsearch

volumes:
  es_data:
  redis_data:
