version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - 9200:9200
    volumes:
      - es_data:/data

  loader:



volumes:
  es_data:
