version: '3.7'

services:

  movie_web:
    container_name: movie_admin
    build:
      context: .
    env_file:
      - .env
    restart: always
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - db-data-4:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    container_name: nginx
    image: nginx:1.19.2
    restart: always
    depends_on:
      - db
      - movie_web
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d:ro
      - ./static/:/static

volumes:
  db-data-4:
