# Generated by Django 3.1 on 2021-06-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='genres_movie', to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='moviepersonrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'actor'), (1, 'director'), (2, 'screenwriter'), (3, 'producer')], verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genres',
            field=models.ManyToManyField(related_name='genres_serial', to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='serialpersonrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'actor'), (1, 'director'), (2, 'screenwriter'), (3, 'producer')], verbose_name='role'),
        ),
    ]
