# Generated by Django 3.1 on 2021-06-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210619_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='genres',
            field=models.ManyToManyField(to='movie.Genre'),
        ),
    ]
